version: '3.9'

services:

    # php
    php:
        container_name: php
        build: ./php
        ports:
            - 80:80
        volumes:
            - ./php/src:/var/www/html
        depends_on:
            - db

    # mysql
    db:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    
    # adminer
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
